### ISSUE TITLE
GET-SO bug

### ISSUE THREAD

**Issue by jevans97utk** [jevans97utk/willitsync#8]
```
$ willitsync get-so -u https://www.archive.arm.gov/metadata/adc/html/wsacrcrcal.html 
Traceback (most recent call last):
  File "/Users/johnevans/anaconda3/envs/willitsync/bin/willitsync", line 11, in <module>
    load_entry_point('openapi-client==1.0.0', 'console_scripts', 'willitsync')()
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/johnevans/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/johnevans/anaconda3/envs/willitsync/lib/python3.7/site-packages/openapi_client-1.0.0-py3.7.egg/openapi_client/__main__.py", line 78, in get_so
AttributeError: 'DevelopersApi' object has no attribute 'parse_landing_page'
```

**Comment by jevans97utk** [comment]
Done
